services:
  postgres:
    image: postgres:16-alpine
    container_name: dsek-scheduler-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: dsek-scheduler
    container_name: dsek-scheduler
    depends_on:
      - postgres
    environment:
      GO_ENV: production

      SERVER_PORT: 8080

      JWKS_ENDPOINT: https://auth.dsek.se/application/o/dev/jwks/
      JWT_ISSUER: https://auth.dsek.se/application/o/dev/
      JWT_AUDIENCE: SvRybUTCGqhNiw2Y3gn1wqt0YxpjW2sv9fbPsUaP

      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

      PASSWORD: supersecretpassword
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:
